services:
  mariadb:
    container_name: mariadb-container
    build: ${REQ_LOC}/mariadb
    volumes:
      - mariadb_data:/var/bin/mysql
    restart: always
    env_file:
      - .env
    networks:
      - default_network
  wordpress:
    container_name: wp-container
    build: ${REQ_LOC}/wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    env_file:
      - .env
    networks:
      - default_network
    depends_on:
      - mariadb
  nginx:
    container_name: nginx-container
    build: ${REQ_LOC}/nginx
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - default_network
    depends_on:
      - wordpress

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/mariadb
      o: bind

networks:
  default_network:
    driver: bridge