services:
  nginx:
    container_name: nginx-container
    build: ${REQ_LOC}/nginx
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - default
    depends_on:
      - wordpress
  wordpress:
    container_name: wp-container
    build: ${REQ_LOC}/wordpress
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    ports:
      - "9000"
    networks:
      - default
    depends_on:
      - mariadb
  mariadb:
    container_name: mariadb-container
    build: ${REQ_LOC}/mariadb
    volumes:
      - mariadb_data:/var/local/bin/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - default

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/mariadb
      o: bind

networks:
  default:
    driver: bridge